name: Enforce Checklist Completion

# The workflow is triggered by pull request events.
# It will run when the PR is opened, synchronized (new commits pushed), or reopened.
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  checklist:
    # This job runs on the latest Ubuntu runner.
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code so we can interact with the PR.
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Check the PR description for the checklist.
      # We fetch the PR body using GitHub's REST API and parse it with jq.
      - name: Check Checklist
        run: |
          # Fetch the pull request body
          PR_BODY=$(curl -s "https://github.com/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r .body)
          echo "$PR_BODY"
          # Check for incomplete checklist items
          if echo "$PR_BODY" | grep -q "\- \[ \]"; then
           echo "Error: Not all checklist items are completed."
           exit 1
          else
           echo "All checklist items are complete."
          fi
