name: Enforce Checklist Completion

on:
  pull_request:
    types: [opened, edited]

jobs:
  checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Check Checklist Completion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch the pull request body using the GitHub API
          PR_BODY=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r .body)

          # Debug: Output the PR body
          echo "Pull Request Body:"
          echo "$PR_BODY"

          # Check for incomplete checklist items
          if echo "$PR_BODY" | grep -q "\- \[ \]"; then
            echo "Error: Not all checklist items are completed."
            exit 1
          else
            echo "All checklist items are complete."
          fi
