name: Enforce Checklist Completion

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited # Re-run workflow when PR description is edited

jobs:
  checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Checklist Completion
        run: |
          # Fetch the pull request body
          PR_BODY=$(curl -s https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | jq -r .body)

          # Check for incomplete checklist items
          if echo "$PR_BODY" | grep -q "\- \[x\]"; then
            echo "Error: Not all checklist items are completed."
            exit 1
          else
            echo "All checklist items are complete."
          fi
